// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudioManager.Infrastructure;

#nullable disable

namespace StudioManager.Infrastructure.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(StudioManagerDbContext))]
    [Migration("20240518165326_AddReservation")]
    partial class AddReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudioManager.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_type_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("initial_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("ix_equipments_equipment_type_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.EquipmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_equipment_types");

                    b.ToTable("equipment_types", (string)null);
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_reservations_equipment_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("StudioManager.Domain.Entities.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipments_equipment_types_equipment_type_id");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("StudioManager.Domain.Entities.Equipment", "Equipment")
                        .WithMany("Reservations")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_equipments_equipment_id");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("StudioManager.Domain.Entities.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
