services:
  StudioManager_DB:
    image: postgres:latest
    container_name: StudioManager_DB
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: StudioManager
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  
  studiomanager.api:
    image: studiomanager.api
    container_name: "studiomanager.api"
    depends_on:
      - "StudioManager_DB"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5000:80
        - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
