services:
  studiomanager.api:
    image: studiomanager.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5000:80
        - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
