services:
  studiomanager.database:
    image: postgres:latest
    container_name: studiomanager.database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: StudioManager
    healthcheck:
      test: "exit 0"
    volumes:
      - ./.containers/studiomanager-db:/var/lib/postgresql/data
    restart: unless-stopped
  
  studiomanager.api:
    image: ${DOCKER_REGISTRY-}studiomanager.api
    container_name: studiomanager.api
    depends_on:
      studiomanager.database:
        condition: service_healthy
    links:
      - studiomanager.database
    build:
      context: .
      dockerfile: StudioManager.API/Dockerfile
    ports:
        - 5000:5000
        - 5001:5001
    environment:
      - ASPNETCORE_URLS=http://+:5001
    restart: unless-stopped
